server:
  port: 7400

#spring:
#  datasource:
#    url: jdbc:mysql://192.168.229.129:3306/test?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&serverTimezone=UTC&useSSL=false
#    username: yazheng
#    password: yazheng123
#    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: info
    org.springframework: info

spring:
  servlet:
    multipart:
      #是否启用 Spring MVC 多分部上传功能
      enabled: true
      #将文件写入磁盘的阀值 。 值可以使用后缀“ MB ”或“ KB ” 来表示兆字节或字节大小
      file-size-threshold: 0
      #指定默认上传的文件夹
      location: f:\\
      #限制单个文件最大大小
      max-file-size: 1MB
      #限制所有文件最大大小
      max-request-size: 10MB

custom:
  security:
    browser:
      login-page: /demo/custom-login.html
      login-type: REDIRECT